"""Add form column to ShinyPokemon model

Revision ID: 03d33f82407e
Revises: 043db4e40474
Create Date: 2024-11-03 12:05:56.267528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d33f82407e'
down_revision = '043db4e40474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shinies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('_dex_name_form_uc', ['dex_number', 'name', 'form'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shinies', schema=None) as batch_op:
        batch_op.drop_constraint('_dex_name_form_uc', type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('form')

    # ### end Alembic commands ###
