"""empty message

Revision ID: 0a9ab47cf703
Revises: cae81e2db626
Create Date: 2024-10-22 11:37:53.575190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9ab47cf703'
down_revision = 'cae81e2db626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.alter_column(
            'dex_number',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            postgresql_using="dex_number::integer",  # Converts VARCHAR to INTEGER
            existing_nullable=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.alter_column('dex_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('first_appearance')

    # ### end Alembic commands ###
