"""Update Costume and PokemonOwnership models

Revision ID: 3a5240c2e45c
Revises: d7058aae613c
Create Date: 2024-11-09 18:25:43.437391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5240c2e45c'
down_revision = 'd7058aae613c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costume_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('costume', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('shiny_released', sa.Boolean(), nullable=True),
    sa.Column('shiny_image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dex_number', 'name', 'costume', name='_dex_name_costume_uc')
    )
    op.create_table('pokemon_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costume_pokemon_id', sa.Integer(), nullable=False),
    sa.Column('brady_own', sa.Boolean(), nullable=True),
    sa.Column('brady_shiny', sa.Boolean(), nullable=True),
    sa.Column('matt_own', sa.Boolean(), nullable=True),
    sa.Column('matt_shiny', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['costume_pokemon_id'], ['costume_pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('costumes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costumes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dex_number', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('costume', sa.VARCHAR(length=100), nullable=False),
    sa.Column('first_appearance', sa.VARCHAR(length=255), nullable=True),
    sa.Column('brady_own', sa.BOOLEAN(), nullable=True),
    sa.Column('brady_lucky', sa.BOOLEAN(), nullable=True),
    sa.Column('matt_own', sa.BOOLEAN(), nullable=True),
    sa.Column('matt_lucky', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pokemon_ownership')
    op.drop_table('costume_pokemon')
    # ### end Alembic commands ###
