"""Remove specials table

Revision ID: 41718bb30cb8
Revises: a2c17d7b40e5
Create Date: 2024-11-14 22:17:07.974243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41718bb30cb8'
down_revision = 'a2c17d7b40e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dex_number', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
