"""Create costumes table and other updates

Revision ID: 6e733442b30a
Revises: da5a02654aac
Create Date: 2024-11-09 23:30:18.459912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e733442b30a'
down_revision = 'da5a02654aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.alter_column('brady_own',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('brady_shiny',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('matt_own',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('matt_shiny',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.alter_column('matt_shiny',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('matt_own',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('brady_shiny',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('brady_own',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
