"""Added user_2_shiny and user_0_shiny columns for Matt ✨ and iPad ✨

Revision ID: 77a89d496765
Revises: c55e9627fc78
Create Date: 2024-11-22 11:45:12.093417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a89d496765'
down_revision = 'c55e9627fc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_2_shiny', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_0_shiny', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('user_0_shiny')
        batch_op.drop_column('user_2_shiny')

    # ### end Alembic commands ###
