"""Add matt_shadow and matt_purified columns to Rocket

Revision ID: 7ad4fe93f840
Revises: 41718bb30cb8
Create Date: 2024-11-15 09:28:22.767569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad4fe93f840'
down_revision = '41718bb30cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brady_shadow', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('brady_purified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('matt_shadow', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('matt_purified', sa.Boolean(), nullable=True))
        batch_op.alter_column('dex_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint('_dex_name_uc', ['dex_number', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.drop_constraint('_dex_name_uc', type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('dex_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('matt_purified')
        batch_op.drop_column('matt_shadow')
        batch_op.drop_column('brady_purified')
        batch_op.drop_column('brady_shadow')

    # ### end Alembic commands ###
