"""empty message

Revision ID: 9ae7b8274197
Revises: 0a9ab47cf703
Create Date: 2024-10-22 12:12:39.211217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae7b8274197'
down_revision = '0a9ab47cf703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.alter_column('dex_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.alter_column('dex_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
