"""Add user-specific fields to Pokemon table

Revision ID: a521d4564132
Revises: d8de2c389ff1
Create Date: 2024-10-29 15:14:04.821644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a521d4564132'
down_revision = 'd8de2c389ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Adding user-specific columns to the pokemon table
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_1_living_dex', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_1_lucky', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_2_living_dex', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_2_lucky', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_0_living_dex', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_0_lucky', sa.Boolean(), nullable=True))

    # Dropping `user_id` columns from other tables (optional if not used anymore)
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('poke_genie', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('shinies', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('specials', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Removing user-specific columns from the pokemon table
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('user_0_lucky')
        batch_op.drop_column('user_0_living_dex')
        batch_op.drop_column('user_2_lucky')
        batch_op.drop_column('user_2_living_dex')
        batch_op.drop_column('user_1_lucky')
        batch_op.drop_column('user_1_living_dex')

    # Re-adding `user_id` columns to the other tables
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_costumes_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_forms_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('poke_genie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_poke_genie_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_rocket_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('shinies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_shinies_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('specials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_specials_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###