"""Add Brady shiny column to Pokemon

Revision ID: c55e9627fc78
Revises: cdbe101a4e2b
Create Date: 2024-11-22 10:08:19.843930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55e9627fc78'
down_revision = 'cdbe101a4e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_1_shiny', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('user_1_shiny')

    # ### end Alembic commands ###
