"""Remove shiny_released column from costumes table

Revision ID: cdbe101a4e2b
Revises: 7ad4fe93f840
Create Date: 2024-11-16 00:05:47.162697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbe101a4e2b'
down_revision = '7ad4fe93f840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.drop_column('shiny_released')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shiny_released', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
