"""Add user-specific dex fields to Pokemon model

Revision ID: ce10b8100b37
Revises: a521d4564132
Create Date: 2024-10-29 20:11:28.825162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce10b8100b37'
down_revision = 'a521d4564132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('note_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_notes_pokemon_id', type_='foreignkey')

    with op.batch_alter_table('owned_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lucky_dex', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('need_on_ipad', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owned_pokemon', schema=None) as batch_op:
        batch_op.drop_column('need_on_ipad')
        batch_op.drop_column('lucky_dex')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_notes_pokemon_id', 'pokemon', ['pokemon_id'], ['id'])
        batch_op.alter_column('note_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
