"""Add ownership and lucky tracking to costumes

Revision ID: d7058aae613c
Revises: 03d33f82407e
Create Date: 2024-11-03 17:33:03.878212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7058aae613c'
down_revision = '03d33f82407e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        # Add new columns with nullable=True initially
        batch_op.add_column(sa.Column('brady_own', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('brady_lucky', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('matt_own', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('matt_lucky', sa.Boolean(), nullable=True))
        
        # Temporarily remove NOT NULL constraints for existing columns
        batch_op.alter_column('dex_number',
               existing_type=sa.INTEGER(),
               nullable=True)  # Change to nullable=True temporarily
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)  # Change to nullable=True temporarily
        batch_op.alter_column('costume',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)  # Change to nullable=True temporarily
    # ### end Alembic commands ###

    # Data update to ensure no NULLs in critical columns
    op.execute("UPDATE costumes SET dex_number = 0 WHERE dex_number IS NULL")
    op.execute("UPDATE costumes SET name = 'Unknown' WHERE name IS NULL")
    op.execute("UPDATE costumes SET costume = 'None' WHERE costume IS NULL")

    # Now enforce NOT NULL constraints
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.alter_column('dex_number', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('name', existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.alter_column('costume', existing_type=sa.VARCHAR(length=100), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumes', schema=None) as batch_op:
        batch_op.alter_column('costume',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('dex_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('matt_lucky')
        batch_op.drop_column('matt_own')
        batch_op.drop_column('brady_lucky')
        batch_op.drop_column('brady_own')
    # ### end Alembic commands ###
