"""Fixed foreign key reference between User and OwnedPokemon

Revision ID: d8de2c389ff1
Revises: da71b55bdfae
Create Date: 2024-10-29 11:41:17.772310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision = 'd8de2c389ff1'
down_revision = 'da71b55bdfae'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)

    # Check for 'fk_costumes_user_id' constraint and drop if exists
    if 'fk_costumes_user_id' in [fk['name'] for fk in inspector.get_foreign_keys('costumes')]:
        with op.batch_alter_table('costumes', schema=None) as batch_op:
            batch_op.drop_constraint('fk_costumes_user_id', type_='foreignkey')
            batch_op.drop_column('user_id')

    if 'fk_forms_user_id' in [fk['name'] for fk in inspector.get_foreign_keys('forms')]:
        with op.batch_alter_table('forms', schema=None) as batch_op:
            batch_op.drop_constraint('fk_forms_user_id', type_='foreignkey')
            batch_op.drop_column('user_id')

    # Handle the 'notes' table foreign key constraint
    if 'fk_notes_user_id' in [fk['name'] for fk in inspector.get_foreign_keys('notes')]:
        with op.batch_alter_table('notes', schema=None) as batch_op:
            batch_op.drop_constraint('fk_notes_user_id', type_='foreignkey')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('note_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_notes_pokemon_id', 'pokemon', ['pokemon_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('owned_pokemon', schema=None) as batch_op:
        batch_op.drop_column('need_on_ipad')

    if 'fk_poke_genie_user_id' in [fk['name'] for fk in inspector.get_foreign_keys('poke_genie')]:
        with op.batch_alter_table('poke_genie', schema=None) as batch_op:
            batch_op.drop_constraint('fk_poke_genie_user_id', type_='foreignkey')
            batch_op.drop_column('user_id')

    if 'fk_rocket_user_id' in [fk['name'] for fk in inspector.get_foreign_keys('rocket')]:
        with op.batch_alter_table('rocket', schema=None) as batch_op:
            batch_op.drop_constraint('fk_rocket_user_id', type_='foreignkey')
            batch_op.drop_column('user_id')

    if 'fk_shinies_user_id' in [fk['name'] for fk in inspector.get_foreign_keys('shinies')]:
        with op.batch_alter_table('shinies', schema=None) as batch_op:
            batch_op.drop_constraint('fk_shinies_user_id', type_='foreignkey')
            batch_op.drop_column('user_id')

    if 'fk_specials_user_id' in [fk['name'] for fk in inspector.get_foreign_keys('specials')]:
        with op.batch_alter_table('specials', schema=None) as batch_op:
            batch_op.drop_constraint('fk_specials_user_id', type_='foreignkey')
            batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('specials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_specials_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('shinies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_shinies_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('rocket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_rocket_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('poke_genie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_poke_genie_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('owned_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need_on_ipad', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_notes_pokemon_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_notes_user_id', 'users', ['user_id'], ['id'])
        batch_op.alter_column('note_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.al
