"""Consolidate Costume model and drop PokemonOwnership table

Revision ID: da5a02654aac
Revises: 3a5240c2e45c
Create Date: 2024-11-09 18:34:50.994979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5a02654aac'
down_revision = '3a5240c2e45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_ownership')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_ownership',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('costume_pokemon_id', sa.INTEGER(), nullable=False),
    sa.Column('brady_own', sa.BOOLEAN(), nullable=True),
    sa.Column('brady_shiny', sa.BOOLEAN(), nullable=True),
    sa.Column('matt_own', sa.BOOLEAN(), nullable=True),
    sa.Column('matt_shiny', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['costume_pokemon_id'], ['costumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
