"""Initial migration

Revision ID: da71b55bdfae
Revises: 
Create Date: 2024-10-26 01:41:22.926208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da71b55bdfae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('costumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('costume', sa.String(length=100), nullable=True),
    sa.Column('first_appearance', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owned_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('have_living_dex', sa.Boolean(), nullable=True),
    sa.Column('need_on_ipad', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poke_genie',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('pokemon_number', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('atk_iv', sa.Integer(), nullable=True),
    sa.Column('def_iv', sa.Integer(), nullable=True),
    sa.Column('sta_iv', sa.Integer(), nullable=True),
    sa.Column('iv_avg', sa.Float(), nullable=True),
    sa.Column('level_min', sa.Float(), nullable=True),
    sa.Column('level_max', sa.Float(), nullable=True),
    sa.Column('quick_move', sa.String(length=50), nullable=True),
    sa.Column('charge_move', sa.String(length=50), nullable=True),
    sa.Column('charge_move_2', sa.String(length=50), nullable=True),
    sa.Column('scan_date', sa.String(length=50), nullable=True),
    sa.Column('original_scan_date', sa.String(length=50), nullable=True),
    sa.Column('catch_date', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('lucky', sa.Integer(), nullable=True),
    sa.Column('shadow_purified', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('dust', sa.Integer(), nullable=True),
    sa.Column('rank_g_pct', sa.Float(), nullable=True),
    sa.Column('rank_g_num', sa.Integer(), nullable=True),
    sa.Column('stat_prod_g', sa.Float(), nullable=True),
    sa.Column('dust_cost_g', sa.Integer(), nullable=True),
    sa.Column('candy_cost_g', sa.Integer(), nullable=True),
    sa.Column('name_g', sa.String(length=50), nullable=True),
    sa.Column('form_g', sa.String(length=50), nullable=True),
    sa.Column('sha_pur_g', sa.Integer(), nullable=True),
    sa.Column('rank_u_pct', sa.Float(), nullable=True),
    sa.Column('rank_u_num', sa.Integer(), nullable=True),
    sa.Column('stat_prod_u', sa.Float(), nullable=True),
    sa.Column('dust_cost_u', sa.Integer(), nullable=True),
    sa.Column('candy_cost_u', sa.Integer(), nullable=True),
    sa.Column('name_u', sa.String(length=50), nullable=True),
    sa.Column('form_u', sa.String(length=50), nullable=True),
    sa.Column('sha_pur_u', sa.Integer(), nullable=True),
    sa.Column('rank_l_pct', sa.Float(), nullable=True),
    sa.Column('rank_l_num', sa.Integer(), nullable=True),
    sa.Column('stat_prod_l', sa.Float(), nullable=True),
    sa.Column('dust_cost_l', sa.Integer(), nullable=True),
    sa.Column('candy_cost_l', sa.Integer(), nullable=True),
    sa.Column('name_l', sa.String(length=50), nullable=True),
    sa.Column('form_l', sa.String(length=50), nullable=True),
    sa.Column('sha_pur_l', sa.Integer(), nullable=True),
    sa.Column('marked_for_pvp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('rocket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shinies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specials')
    op.drop_table('shinies')
    op.drop_table('rocket')
    op.drop_table('poke_genie')
    op.drop_table('owned_pokemon')
    op.drop_table('notes')
    op.drop_table('forms')
    op.drop_table('costumes')
    op.drop_table('users')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
