"""Initial migration with updated Pokemon model

Revision ID: eb5cadf6028c
Revises: 
Create Date: 2024-11-24 09:41:25.848707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5cadf6028c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('shiny_released', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('brady_living_dex', sa.Boolean(), nullable=True),
    sa.Column('brady_shiny', sa.Boolean(), nullable=True),
    sa.Column('brady_lucky', sa.Boolean(), nullable=True),
    sa.Column('matt_living_dex', sa.Boolean(), nullable=True),
    sa.Column('matt_shiny', sa.Boolean(), nullable=True),
    sa.Column('matt_lucky', sa.Boolean(), nullable=True),
    sa.Column('ipad_living_dex', sa.Boolean(), nullable=True),
    sa.Column('ipad_shiny', sa.Boolean(), nullable=True),
    sa.Column('ipad_lucky', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dex_number')
    )
    op.create_table('owned_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('have_living_dex', sa.Boolean(), nullable=True),
    sa.Column('lucky_dex', sa.Boolean(), nullable=True),
    sa.Column('need_on_ipad', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owned_pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
